const x = 10

try {
    x = 2
    console.log('deu bom')
} catch (error) {
    console.log(`Erro: ${error}`)
}